name: Build iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: actions/setup-xcode@v1
    - name: Install dependencies
      run: pod install
    - name: Build app
      run: xcodebuild -workspace socrates.xcworkspace -scheme socrates
    - name: Save build artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyApp
        path: path/to/socrates.app

